### ISSUE TITLE
Doesn't work with Houdini 17

### ISSUE THREAD

**Issue by ChrBohm** [paulwinex/pw_MultiScriptEditor#6]
Seems like the editor doesn't work anymore in Houdini 17.
I always get this error:

```
Traceback (most recent call last):
  File "editor", line 5, in <module>
  File "C:/houdini\multi_script_editor\__init__.py", line 17, in showHoudini
    size=size, pane=pane, replacePyPanel=replacePyPanel, hideTitleMenu=hideTitleMenu)
  File "C:/houdini\multi_script_editor\managers\_houdini.py", line 26, in show
    hqt.show(scriptEditor.scriptEditorClass, *args, **kwargs)
  File "hqt.py", line 99, in show
    return showUi14( cls, name=name, floating=floating, position=position, size=size, pane=pane, replacePyPanel=replacePyPanel, hideTitleMenu=hideTitleMenu, dialog=dialog,useThisPanel=useThisPanel)
  File "hqt.py", line 253, in showUi14
    hou.pypanel.installFile(panFile)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.352/houdini/python2.7libs\hou.py", line 47926, in installFile
    return _hou.pypanel_installFile(*args)
OperationFailed: The attempted operation failed.
Invalid file
```

Also there is no multi_script_editor_17.pypanel in /managers

Thanks!

**Comment by mushogenshin** [comment]
Yes I have troubles making it work in Houdini 18 as well. Also I think the file
`/managers/houdini/multi_script_editor_17.pypanel` is missing.

Thanks!
